services:
  mysql:
    container_name: mysql-bsn
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yevs2007
      MYSQL_DATABASE: mlf_db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local